# Stage 1 - builder
FROM python:3.13-alpine AS builder

WORKDIR /app

COPY requirements.txt /app/

RUN pip install --no-cache-dir -r requirements.txt


# Stage 2 - final image
FROM python:3.13-alpine

WORKDIR /app

RUN apk add --no-cache make bash curl jq

COPY --from=builder /usr/local/lib/python3.13/site-packages /usr/local/lib/python3.13/site-packages
COPY --from=builder /usr/local/bin /usr/local/bin

COPY . .

RUN chmod +x /app/entrypoint.sh

EXPOSE 5000

ENTRYPOINT ["/app/entrypoint.sh"]