from .home import home_bp
from .assignment import assignment_bp
from .course_schedule import course_schedule_bp
from .course import course_bp
from .department import department_bp
from .enrollment import enrollment_bp
from .instructor import instructor_bp
from .program import program_bp
from .student import student_bp
from .term import term_bp
